# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# namespace: $TARGET_NAMESPACE

# images:
#   - name: $AZURE_VOTE_IMAGE_REPO/azure-vote-front
#     newTag: $FRONTEND_IMAGE
#   - name: $AZURE_VOTE_IMAGE_REPO/azure-vote-back
#     newTag: $BACKEND_IMAGE
# resources:
  # - ../../helm/template/az-vote-back-deployment.yaml
  # - ../../helm/template/az-vote-svc.yaml
  # - ../../helm/template/az-vote-front-deployment.yaml
  # - ../../helm/template/az-vote-front-ingress.yaml
  # - ../../helm/template/az-vote-loadbalancer-svc.yaml
  #- manifests.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: $TARGET_NAMESPACE
 
helmCharts:
  - name: azure-vote
    path: helm
    releaseName: azure-vote-release
    valuesFile: helm/values.yaml
 
# Include other resources if needed
resources:
  - ../manifests/other-manifest.yaml
