apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: $AZURE_VOTE_IMAGE_REPO/azure-vote-front
    newTag: $FRONTEND_IMAGE
  - name: $AZURE_VOTE_IMAGE_REPO/azure-vote-back
    newTag: $BACKEND_IMAGE
resources:
  - ./template/az-vote-back-deployment.yaml
  - ./template/az-vote-svc.yaml
  - ./template/az-vote-front-deployment.yaml
  - ./template/az-vote-front-ingress.yaml
  - ./template/az-vote-loadbalancer-svc.yaml
  # - manifests.yaml
helm:
  - name: template
    path: ./template/az-vote-back-deployment.yaml
          ./template/az-vote-svc.yaml
          ./template/az-vote-front-deployment.yaml
          ./template/az-vote-front-ingress.yaml
          ./template/az-vote-loadbalancer-svc.yaml
          
          

